# Generated by Django 4.2.13 on 2024-05-18 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="categories",
            table="category",
        ),
    ]
