# Generated by Django 4.2.13 on 2024-05-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_categories_options_alter_categories_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="URL"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=4,
                verbose_name="Скидка в процентах",
            ),
        ),
    ]
