# Generated by Django 4.2.13 on 2024-05-27 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_alter_categories_slug_alter_products_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
